/**
 * ⚠️ ملف مُولَّد آلياً — لا تعدّله يدوياً.
 * لإعادة التوليد: npm run data:geo
 * المصدر: scripts/vendor/algeria_cities.json (MIT — othmanus/algeria-cities)
 * التصحيحات الفرنسية: scripts/generate-geo-data.mjs (FR_OVERRIDES)
 * البلديات: 256 بلدية رسمية عبر 7 ولايات نشطة.
 */
export interface CommuneRecord {
  /** المعرف الرسمي العام (ثابت عبر إعادة التوليد) */
  readonly id: number;
  readonly wilayaCode: number;
  readonly slug: string;
  readonly nameAr: string;
  readonly nameFr: string;
  readonly dairaAr: string;
  readonly dairaFr: string;
}

export const COMMUNES = [
  {id: 284, wilayaCode: 9, slug: 'ain-romana', nameAr: 'عين الرمانة', nameFr: 'Aïn Romana', dairaAr: 'موزاية', dairaFr: 'Mouzaia'},
  {id: 285, wilayaCode: 9, slug: 'beni-mered', nameAr: 'بني مراد', nameFr: 'Beni Mered', dairaAr: 'أولاد يعيش', dairaFr: 'Ouled Yaich'},
  {id: 286, wilayaCode: 9, slug: 'beni-tamou', nameAr: 'بني تامو', nameFr: 'Beni Tamou', dairaAr: 'وادي العلايق', dairaFr: 'Oued El Alleug'},
  {id: 287, wilayaCode: 9, slug: 'ben-khelil', nameAr: 'بن خليل', nameFr: 'Ben Khelil', dairaAr: 'وادي العلايق', dairaFr: 'Oued El Alleug'},
  {id: 288, wilayaCode: 9, slug: 'blida', nameAr: 'البليدة', nameFr: 'Blida', dairaAr: 'البليدة', dairaFr: 'Blida'},
  {id: 289, wilayaCode: 9, slug: 'bouarfa', nameAr: 'بوعرفة', nameFr: 'Bouarfa', dairaAr: 'البليدة', dairaFr: 'Blida'},
  {id: 290, wilayaCode: 9, slug: 'boufarik', nameAr: 'بوفاريك', nameFr: 'Boufarik', dairaAr: 'بوفاريك', dairaFr: 'Boufarik'},
  {id: 291, wilayaCode: 9, slug: 'bougara', nameAr: 'بوقرة', nameFr: 'Bougara', dairaAr: 'بوقرة', dairaFr: 'Bougara'},
  {id: 292, wilayaCode: 9, slug: 'bouinan', nameAr: 'بوعينان', nameFr: 'Bouinan', dairaAr: 'بوعينان', dairaFr: 'Bouinan'},
  {id: 293, wilayaCode: 9, slug: 'chebli', nameAr: 'الشبلي', nameFr: 'Chébli', dairaAr: 'بوعينان', dairaFr: 'Bouinan'},
  {id: 294, wilayaCode: 9, slug: 'chiffa', nameAr: 'الشفة', nameFr: 'Chiffa', dairaAr: 'موزاية', dairaFr: 'Mouzaia'},
  {id: 295, wilayaCode: 9, slug: 'chrea', nameAr: 'الشريعة', nameFr: 'Chréa', dairaAr: 'أولاد يعيش', dairaFr: 'Ouled Yaich'},
  {id: 296, wilayaCode: 9, slug: 'djebabra', nameAr: 'جبابرة', nameFr: 'Djebabra', dairaAr: 'مفتاح', dairaFr: 'Meftah'},
  {id: 297, wilayaCode: 9, slug: 'el-affroun', nameAr: 'العفرون', nameFr: 'El Affroun', dairaAr: 'العفرون', dairaFr: 'El Affroun'},
  {id: 298, wilayaCode: 9, slug: 'guerouaou', nameAr: 'قرواو', nameFr: 'Guerouaou', dairaAr: 'بوفاريك', dairaFr: 'Boufarik'},
  {id: 299, wilayaCode: 9, slug: 'hammam-melouane', nameAr: 'حمام ملوان', nameFr: 'Hammam Melouane', dairaAr: 'بوقرة', dairaFr: 'Bougara'},
  {id: 300, wilayaCode: 9, slug: 'larbaa', nameAr: 'الأربعاء', nameFr: 'Larbaâ', dairaAr: 'الأربعاء', dairaFr: 'Larbaa'},
  {id: 301, wilayaCode: 9, slug: 'meftah', nameAr: 'مفتاح', nameFr: 'Meftah', dairaAr: 'مفتاح', dairaFr: 'Meftah'},
  {id: 302, wilayaCode: 9, slug: 'mouzaia', nameAr: 'موزاية', nameFr: 'Mouzaïa', dairaAr: 'موزاية', dairaFr: 'Mouzaia'},
  {id: 303, wilayaCode: 9, slug: 'oued-djer', nameAr: 'وادي جر', nameFr: 'Oued Djer', dairaAr: 'العفرون', dairaFr: 'El Affroun'},
  {id: 304, wilayaCode: 9, slug: 'oued-el-alleug', nameAr: 'وادي العلايق', nameFr: 'Oued El Alleug', dairaAr: 'وادي العلايق', dairaFr: 'Oued El Alleug'},
  {id: 305, wilayaCode: 9, slug: 'ouled-slama', nameAr: 'اولاد سلامة', nameFr: 'Ouled Slama', dairaAr: 'بوقرة', dairaFr: 'Bougara'},
  {id: 306, wilayaCode: 9, slug: 'ouled-yaich', nameAr: 'أولاد يعيش', nameFr: 'Ouled Yaïch', dairaAr: 'أولاد يعيش', dairaFr: 'Ouled Yaich'},
  {id: 307, wilayaCode: 9, slug: 'souhane', nameAr: 'صوحان', nameFr: 'Souhane', dairaAr: 'الأربعاء', dairaFr: 'Larbaa'},
  {id: 308, wilayaCode: 9, slug: 'soumaa', nameAr: 'الصومعة', nameFr: 'Soumaâ', dairaAr: 'بوفاريك', dairaFr: 'Boufarik'},
  {id: 554, wilayaCode: 16, slug: 'ain-benian', nameAr: 'عين بنيان', nameFr: 'Aïn Benian', dairaAr: 'الشراقة', dairaFr: 'Cheraga'},
  {id: 555, wilayaCode: 16, slug: 'ain-taya', nameAr: 'عين طاية', nameFr: 'Aïn Taya', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 556, wilayaCode: 16, slug: 'alger-centre', nameAr: 'الجزائر الوسطى', nameFr: 'Alger Centre', dairaAr: 'سيدي امحمد', dairaFr: 'Sidi M\'hamed'},
  {id: 557, wilayaCode: 16, slug: 'bab-el-oued', nameAr: 'باب الوادي', nameFr: 'Bab El Oued', dairaAr: 'باب الوادي', dairaFr: 'Bab El Oued'},
  {id: 558, wilayaCode: 16, slug: 'bab-ezzouar', nameAr: 'باب الزوار', nameFr: 'Bab Ezzouar', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 559, wilayaCode: 16, slug: 'baba-hassen', nameAr: 'بابا حسن', nameFr: 'Baba Hassen', dairaAr: 'الدرارية', dairaFr: 'Draria'},
  {id: 560, wilayaCode: 16, slug: 'bachdjerrah', nameAr: 'باش جراح', nameFr: 'Bachdjerrah', dairaAr: 'الحراش', dairaFr: 'El Harrach'},
  {id: 561, wilayaCode: 16, slug: 'baraki', nameAr: 'براقي', nameFr: 'Baraki', dairaAr: 'براقي', dairaFr: 'Baraki'},
  {id: 562, wilayaCode: 16, slug: 'ben-aknoun', nameAr: 'ابن عكنون', nameFr: 'Ben Aknoun', dairaAr: 'بوزريعة', dairaFr: 'Bouzareah'},
  {id: 563, wilayaCode: 16, slug: 'beni-messous', nameAr: 'بني مسوس', nameFr: 'Beni Messous', dairaAr: 'بوزريعة', dairaFr: 'Bouzareah'},
  {id: 564, wilayaCode: 16, slug: 'bir-mourad-rais', nameAr: 'بئر مراد رايس', nameFr: 'Bir Mourad Raïs', dairaAr: 'بئر مراد رايس', dairaFr: 'Bir Mourad Rais'},
  {id: 565, wilayaCode: 16, slug: 'birkhadem', nameAr: 'بئر خادم', nameFr: 'Birkhadem', dairaAr: 'بئر مراد رايس', dairaFr: 'Bir Mourad Rais'},
  {id: 566, wilayaCode: 16, slug: 'bir-touta', nameAr: 'بئر توتة', nameFr: 'Bir Touta', dairaAr: 'بئر توتة', dairaFr: 'Birtouta'},
  {id: 567, wilayaCode: 16, slug: 'bologhine', nameAr: 'بولوغين بن زيري', nameFr: 'Bologhine', dairaAr: 'باب الوادي', dairaFr: 'Bab El Oued'},
  {id: 568, wilayaCode: 16, slug: 'bordj-el-bahri', nameAr: 'برج البحري', nameFr: 'Bordj El Bahri', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 569, wilayaCode: 16, slug: 'bordj-el-kiffan', nameAr: 'برج الكيفان', nameFr: 'Bordj El Kiffan', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 570, wilayaCode: 16, slug: 'bourouba', nameAr: 'بوروبة', nameFr: 'Bourouba', dairaAr: 'الحراش', dairaFr: 'El Harrach'},
  {id: 571, wilayaCode: 16, slug: 'bouzareah', nameAr: 'بوزريعة', nameFr: 'Bouzaréah', dairaAr: 'بوزريعة', dairaFr: 'Bouzareah'},
  {id: 572, wilayaCode: 16, slug: 'casbah', nameAr: 'القصبة', nameFr: 'Casbah', dairaAr: 'باب الوادي', dairaFr: 'Bab El Oued'},
  {id: 573, wilayaCode: 16, slug: 'cheraga', nameAr: 'الشراقة', nameFr: 'Chéraga', dairaAr: 'الشراقة', dairaFr: 'Cheraga'},
  {id: 574, wilayaCode: 16, slug: 'dar-el-beida', nameAr: 'الدار البيضاء', nameFr: 'Dar El Beida', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 575, wilayaCode: 16, slug: 'dely-ibrahim', nameAr: 'دالي ابراهيم', nameFr: 'Dely Ibrahim', dairaAr: 'الشراقة', dairaFr: 'Cheraga'},
  {id: 576, wilayaCode: 16, slug: 'djasr-kasentina', nameAr: 'جسر قسنطينة', nameFr: 'Djasr Kasentina', dairaAr: 'بئر مراد رايس', dairaFr: 'Bir Mourad Rais'},
  {id: 577, wilayaCode: 16, slug: 'douera', nameAr: 'الدويرة', nameFr: 'Douéra', dairaAr: 'الدرارية', dairaFr: 'Draria'},
  {id: 578, wilayaCode: 16, slug: 'draria', nameAr: 'الدرارية', nameFr: 'Draria', dairaAr: 'الدرارية', dairaFr: 'Draria'},
  {id: 579, wilayaCode: 16, slug: 'el-achour', nameAr: 'العاشور', nameFr: 'El Achour', dairaAr: 'الدرارية', dairaFr: 'Draria'},
  {id: 580, wilayaCode: 16, slug: 'el-biar', nameAr: 'الابيار', nameFr: 'El Biar', dairaAr: 'بوزريعة', dairaFr: 'Bouzareah'},
  {id: 581, wilayaCode: 16, slug: 'el-harrach', nameAr: 'الحراش', nameFr: 'El Harrach', dairaAr: 'الحراش', dairaFr: 'El Harrach'},
  {id: 582, wilayaCode: 16, slug: 'el-madania', nameAr: 'المدنية', nameFr: 'El Madania', dairaAr: 'سيدي امحمد', dairaFr: 'Sidi M\'hamed'},
  {id: 583, wilayaCode: 16, slug: 'el-magharia', nameAr: 'المغارية', nameFr: 'El Magharia', dairaAr: 'حسين داي', dairaFr: 'Hussein Dey'},
  {id: 584, wilayaCode: 16, slug: 'el-marsa', nameAr: 'المرسى', nameFr: 'El Marsa', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 585, wilayaCode: 16, slug: 'el-mouradia', nameAr: 'المرادية', nameFr: 'El Mouradia', dairaAr: 'سيدي امحمد', dairaFr: 'Sidi M\'hamed'},
  {id: 586, wilayaCode: 16, slug: 'el-hammamet', nameAr: 'الحمامات', nameFr: 'El Hammamet', dairaAr: 'الشراقة', dairaFr: 'Cheraga'},
  {id: 587, wilayaCode: 16, slug: 'h-raoua', nameAr: 'هراوة', nameFr: 'H\'raoua', dairaAr: 'الرويبة', dairaFr: 'Rouiba'},
  {id: 588, wilayaCode: 16, slug: 'hussein-dey', nameAr: 'حسين داي', nameFr: 'Hussein Dey', dairaAr: 'حسين داي', dairaFr: 'Hussein Dey'},
  {id: 589, wilayaCode: 16, slug: 'hydra', nameAr: 'حيدرة', nameFr: 'Hydra', dairaAr: 'بئر مراد رايس', dairaFr: 'Bir Mourad Rais'},
  {id: 590, wilayaCode: 16, slug: 'khraicia', nameAr: 'الخرايسية', nameFr: 'Khraicia', dairaAr: 'الدرارية', dairaFr: 'Draria'},
  {id: 591, wilayaCode: 16, slug: 'kouba', nameAr: 'القبة', nameFr: 'Kouba', dairaAr: 'حسين داي', dairaFr: 'Hussein Dey'},
  {id: 592, wilayaCode: 16, slug: 'les-eucalyptus', nameAr: 'الكاليتوس', nameFr: 'Les Eucalyptus', dairaAr: 'براقي', dairaFr: 'Baraki'},
  {id: 593, wilayaCode: 16, slug: 'mahelma', nameAr: 'المعالمة', nameFr: 'Mahelma', dairaAr: 'زرالدة', dairaFr: 'Zeralda'},
  {id: 594, wilayaCode: 16, slug: 'belouizdad', nameAr: 'محمد بلوزداد', nameFr: 'Belouizdad', dairaAr: 'حسين داي', dairaFr: 'Hussein Dey'},
  {id: 595, wilayaCode: 16, slug: 'mohammadia', nameAr: 'المحمدية', nameFr: 'Mohammadia', dairaAr: 'الدار البيضاء', dairaFr: 'Dar El Beida'},
  {id: 596, wilayaCode: 16, slug: 'oued-koriche', nameAr: 'وادي قريش', nameFr: 'Oued Koriche', dairaAr: 'باب الوادي', dairaFr: 'Bab El Oued'},
  {id: 597, wilayaCode: 16, slug: 'oued-smar', nameAr: 'وادي السمار', nameFr: 'Oued Smar', dairaAr: 'الحراش', dairaFr: 'El Harrach'},
  {id: 598, wilayaCode: 16, slug: 'ouled-chebel', nameAr: 'اولاد شبل', nameFr: 'Ouled Chebel', dairaAr: 'بئر توتة', dairaFr: 'Birtouta'},
  {id: 599, wilayaCode: 16, slug: 'ouled-fayet', nameAr: 'اولاد فايت', nameFr: 'Ouled Fayet', dairaAr: 'الشراقة', dairaFr: 'Cheraga'},
  {id: 600, wilayaCode: 16, slug: 'rahmania', nameAr: 'الرحمانية', nameFr: 'Rahmania', dairaAr: 'زرالدة', dairaFr: 'Zeralda'},
  {id: 601, wilayaCode: 16, slug: 'rais-hamidou', nameAr: 'الرايس حميدو', nameFr: 'Raïs Hamidou', dairaAr: 'باب الوادي', dairaFr: 'Bab El Oued'},
  {id: 602, wilayaCode: 16, slug: 'reghaia', nameAr: 'رغاية', nameFr: 'Reghaïa', dairaAr: 'الرويبة', dairaFr: 'Rouiba'},
  {id: 603, wilayaCode: 16, slug: 'rouiba', nameAr: 'الرويبة', nameFr: 'Rouïba', dairaAr: 'الرويبة', dairaFr: 'Rouiba'},
  {id: 604, wilayaCode: 16, slug: 'saoula', nameAr: 'السحاولة', nameFr: 'Saoula', dairaAr: 'بئر مراد رايس', dairaFr: 'Bir Mourad Rais'},
  {id: 605, wilayaCode: 16, slug: 'sidi-m-hamed', nameAr: 'سيدي امحمد', nameFr: 'Sidi M\'Hamed', dairaAr: 'سيدي امحمد', dairaFr: 'Sidi M\'hamed'},
  {id: 606, wilayaCode: 16, slug: 'sidi-moussa', nameAr: 'سيدي موسى', nameFr: 'Sidi Moussa', dairaAr: 'براقي', dairaFr: 'Baraki'},
  {id: 607, wilayaCode: 16, slug: 'souidania', nameAr: 'سويدانية', nameFr: 'Souidania', dairaAr: 'زرالدة', dairaFr: 'Zeralda'},
  {id: 608, wilayaCode: 16, slug: 'staoueli', nameAr: 'سطاوالي', nameFr: 'Staouéli', dairaAr: 'زرالدة', dairaFr: 'Zeralda'},
  {id: 609, wilayaCode: 16, slug: 'tessala-el-merdja', nameAr: 'تسالة المرجة', nameFr: 'Tessala El Merdja', dairaAr: 'بئر توتة', dairaFr: 'Birtouta'},
  {id: 610, wilayaCode: 16, slug: 'zeralda', nameAr: 'زرالدة', nameFr: 'Zéralda', dairaAr: 'زرالدة', dairaFr: 'Zeralda'},
  {id: 675, wilayaCode: 19, slug: 'ain-abessa', nameAr: 'عين عباسة', nameFr: 'Aïn Abessa', dairaAr: 'عين أرنات', dairaFr: 'Ain Arnat'},
  {id: 676, wilayaCode: 19, slug: 'ain-arnat', nameAr: 'عين أرنات', nameFr: 'Aïn Arnat', dairaAr: 'عين أرنات', dairaFr: 'Ain Arnat'},
  {id: 677, wilayaCode: 19, slug: 'ain-azel', nameAr: 'عين أزال', nameFr: 'Aïn Azel', dairaAr: 'عين أزال', dairaFr: 'Ain Azel'},
  {id: 678, wilayaCode: 19, slug: 'ain-el-kebira', nameAr: 'عين الكبيرة', nameFr: 'Aïn El Kebira', dairaAr: 'عين الكبيرة', dairaFr: 'Ain El Kebira'},
  {id: 679, wilayaCode: 19, slug: 'ain-lahdjar', nameAr: 'عين الحجر', nameFr: 'Aïn Lahdjar', dairaAr: 'عين أزال', dairaFr: 'Ain Azel'},
  {id: 680, wilayaCode: 19, slug: 'ain-oulmene', nameAr: 'عين ولمان', nameFr: 'Aïn Oulmene', dairaAr: 'عين ولمان', dairaFr: 'Ain Oulmene'},
  {id: 681, wilayaCode: 19, slug: 'ain-legradj', nameAr: 'عين لقراج', nameFr: 'Aïn Legradj', dairaAr: 'بني ورتيلان', dairaFr: 'Beni Ourtilane'},
  {id: 682, wilayaCode: 19, slug: 'ain-roua', nameAr: 'عين الروى', nameFr: 'Aïn Roua', dairaAr: 'بوقاعة', dairaFr: 'Bougaa'},
  {id: 683, wilayaCode: 19, slug: 'ain-sebt', nameAr: 'عين السبت', nameFr: 'Aïn Sebt', dairaAr: 'بني عزيز', dairaFr: 'Beni Aziz'},
  {id: 684, wilayaCode: 19, slug: 'ait-naoual-mezada', nameAr: 'أيت نوال مزادة', nameFr: 'Ait Naoual Mezada', dairaAr: 'بوعنداس', dairaFr: 'Bouandas'},
  {id: 685, wilayaCode: 19, slug: 'ait-tizi', nameAr: 'ايت تيزي', nameFr: 'Aït Tizi', dairaAr: 'بوعنداس', dairaFr: 'Bouandas'},
  {id: 686, wilayaCode: 19, slug: 'amoucha', nameAr: 'عموشة', nameFr: 'Amoucha', dairaAr: 'عموشة', dairaFr: 'Amoucha'},
  {id: 687, wilayaCode: 19, slug: 'babor', nameAr: 'بابور', nameFr: 'Babor', dairaAr: 'بابور', dairaFr: 'Babor'},
  {id: 688, wilayaCode: 19, slug: 'bazer-sakhra', nameAr: 'بازر سكرة', nameFr: 'Bazer Sakhra', dairaAr: 'العلمة', dairaFr: 'El Eulma'},
  {id: 689, wilayaCode: 19, slug: 'beidha-bordj', nameAr: 'بيضاء برج', nameFr: 'Beidha Bordj', dairaAr: 'عين أزال', dairaFr: 'Ain Azel'},
  {id: 690, wilayaCode: 19, slug: 'bellaa', nameAr: 'بلاعة', nameFr: 'Bellaa', dairaAr: 'بئر العرش', dairaFr: 'Bir El Arch'},
  {id: 691, wilayaCode: 19, slug: 'beni-chebana', nameAr: 'بني شبانة', nameFr: 'Beni Chebana', dairaAr: 'بني ورتيلان', dairaFr: 'Beni Ourtilane'},
  {id: 692, wilayaCode: 19, slug: 'beni-fouda', nameAr: 'بني فودة', nameFr: 'Beni Fouda', dairaAr: 'جميلة', dairaFr: 'Djemila'},
  {id: 693, wilayaCode: 19, slug: 'beni-ourtilane', nameAr: 'بني ورتيلان', nameFr: 'Beni Ourtilane', dairaAr: 'بني ورتيلان', dairaFr: 'Beni Ourtilane'},
  {id: 694, wilayaCode: 19, slug: 'beni-oussine', nameAr: 'بني وسين', nameFr: 'Beni Oussine', dairaAr: 'بوقاعة', dairaFr: 'Bougaa'},
  {id: 695, wilayaCode: 19, slug: 'beni-aziz', nameAr: 'بني عزيز', nameFr: 'Beni Aziz', dairaAr: 'بني عزيز', dairaFr: 'Beni Aziz'},
  {id: 696, wilayaCode: 19, slug: 'beni-mouhli', nameAr: 'بني موحلي', nameFr: 'Beni Mouhli', dairaAr: 'بني ورتيلان', dairaFr: 'Beni Ourtilane'},
  {id: 697, wilayaCode: 19, slug: 'bir-haddada', nameAr: 'بئر حدادة', nameFr: 'Bir Haddada', dairaAr: 'عين أزال', dairaFr: 'Ain Azel'},
  {id: 698, wilayaCode: 19, slug: 'bir-el-arch', nameAr: 'بئر العرش', nameFr: 'Bir El Arch', dairaAr: 'بئر العرش', dairaFr: 'Bir El Arch'},
  {id: 699, wilayaCode: 19, slug: 'bouandas', nameAr: 'بوعنداس', nameFr: 'Bouandas', dairaAr: 'بوعنداس', dairaFr: 'Bouandas'},
  {id: 700, wilayaCode: 19, slug: 'bougaa', nameAr: 'بوقاعة', nameFr: 'Bougaâ', dairaAr: 'بوقاعة', dairaFr: 'Bougaa'},
  {id: 701, wilayaCode: 19, slug: 'bousselam', nameAr: 'بوسلام', nameFr: 'Bousselam', dairaAr: 'بوعنداس', dairaFr: 'Bouandas'},
  {id: 702, wilayaCode: 19, slug: 'boutaleb', nameAr: 'بوطالب', nameFr: 'Boutaleb', dairaAr: 'صالح باي', dairaFr: 'Salah Bey'},
  {id: 703, wilayaCode: 19, slug: 'dehamcha', nameAr: 'الدهامشة', nameFr: 'Dehamcha', dairaAr: 'عين الكبيرة', dairaFr: 'Ain El Kebira'},
  {id: 704, wilayaCode: 19, slug: 'djemila', nameAr: 'جميلة', nameFr: 'Djemila', dairaAr: 'جميلة', dairaFr: 'Djemila'},
  {id: 705, wilayaCode: 19, slug: 'draa-kebila', nameAr: 'ذراع قبيلة', nameFr: 'Draa Kebila', dairaAr: 'حمام قرقور', dairaFr: 'Hammam Guergour'},
  {id: 706, wilayaCode: 19, slug: 'el-eulma', nameAr: 'العلمة', nameFr: 'El Eulma', dairaAr: 'العلمة', dairaFr: 'El Eulma'},
  {id: 707, wilayaCode: 19, slug: 'el-ouricia', nameAr: 'أوريسيا', nameFr: 'El Ouricia', dairaAr: 'عين أرنات', dairaFr: 'Ain Arnat'},
  {id: 708, wilayaCode: 19, slug: 'el-ouldja', nameAr: 'الولجة', nameFr: 'El Ouldja', dairaAr: 'بئر العرش', dairaFr: 'Bir El Arch'},
  {id: 709, wilayaCode: 19, slug: 'guellal', nameAr: 'قلال', nameFr: 'Guellal', dairaAr: 'عين ولمان', dairaFr: 'Ain Oulmene'},
  {id: 710, wilayaCode: 19, slug: 'guelta-zerka', nameAr: 'قلتة زرقاء', nameFr: 'Guelta Zerka', dairaAr: 'العلمة', dairaFr: 'El Eulma'},
  {id: 711, wilayaCode: 19, slug: 'guenzet', nameAr: 'قنزات', nameFr: 'Guenzet', dairaAr: 'قنزات', dairaFr: 'Guenzet'},
  {id: 712, wilayaCode: 19, slug: 'guidjel', nameAr: 'قجال', nameFr: 'Guidjel', dairaAr: 'قجال', dairaFr: 'Guidjel'},
  {id: 713, wilayaCode: 19, slug: 'hammam-soukhna', nameAr: 'حمام السخنة', nameFr: 'Hammam Soukhna', dairaAr: 'حمام السخنة', dairaFr: 'Hammam Sokhna'},
  {id: 714, wilayaCode: 19, slug: 'hamma', nameAr: 'الحامة', nameFr: 'Hamma', dairaAr: 'صالح باي', dairaFr: 'Salah Bey'},
  {id: 715, wilayaCode: 19, slug: 'hammam-guergour', nameAr: 'حمام قرقور', nameFr: 'Hammam Guergour', dairaAr: 'حمام قرقور', dairaFr: 'Hammam Guergour'},
  {id: 716, wilayaCode: 19, slug: 'harbil', nameAr: 'حربيل', nameFr: 'Harbil', dairaAr: 'قنزات', dairaFr: 'Guenzet'},
  {id: 717, wilayaCode: 19, slug: 'kasr-el-abtal', nameAr: 'قصر الابطال', nameFr: 'Kasr El Abtal', dairaAr: 'عين ولمان', dairaFr: 'Ain Oulmene'},
  {id: 718, wilayaCode: 19, slug: 'maaouia', nameAr: 'معاوية', nameFr: 'Maaouia', dairaAr: 'بني عزيز', dairaFr: 'Beni Aziz'},
  {id: 719, wilayaCode: 19, slug: 'maouaklane', nameAr: 'ماوكلان', nameFr: 'Maouaklane', dairaAr: 'ماوكلان', dairaFr: 'Maoklane'},
  {id: 720, wilayaCode: 19, slug: 'mezloug', nameAr: 'مزلوق', nameFr: 'Mezloug', dairaAr: 'عين أرنات', dairaFr: 'Ain Arnat'},
  {id: 721, wilayaCode: 19, slug: 'oued-el-bared', nameAr: 'واد البارد', nameFr: 'Oued El Bared', dairaAr: 'عموشة', dairaFr: 'Amoucha'},
  {id: 722, wilayaCode: 19, slug: 'ouled-addouane', nameAr: 'أولاد عدوان', nameFr: 'Ouled Addouane', dairaAr: 'عين الكبيرة', dairaFr: 'Ain El Kebira'},
  {id: 723, wilayaCode: 19, slug: 'ouled-sabor', nameAr: 'أولاد صابر', nameFr: 'Ouled Sabor', dairaAr: 'قجال', dairaFr: 'Guidjel'},
  {id: 724, wilayaCode: 19, slug: 'ouled-si-ahmed', nameAr: 'أولاد سي أحمد', nameFr: 'Ouled Si Ahmed', dairaAr: 'عين ولمان', dairaFr: 'Ain Oulmene'},
  {id: 725, wilayaCode: 19, slug: 'ouled-tebben', nameAr: 'أولاد تبان', nameFr: 'Ouled Tebben', dairaAr: 'صالح باي', dairaFr: 'Salah Bey'},
  {id: 726, wilayaCode: 19, slug: 'rosfa', nameAr: 'الرصفة', nameFr: 'Rosfa', dairaAr: 'صالح باي', dairaFr: 'Salah Bey'},
  {id: 727, wilayaCode: 19, slug: 'salah-bey', nameAr: 'صالح باي', nameFr: 'Salah Bey', dairaAr: 'صالح باي', dairaFr: 'Salah Bey'},
  {id: 728, wilayaCode: 19, slug: 'serdj-el-ghoul', nameAr: 'سرج الغول', nameFr: 'Serdj El Ghoul', dairaAr: 'بابور', dairaFr: 'Babor'},
  {id: 729, wilayaCode: 19, slug: 'setif', nameAr: 'سطيف', nameFr: 'Sétif', dairaAr: 'سطيف', dairaFr: 'Setif'},
  {id: 730, wilayaCode: 19, slug: 'tachouda', nameAr: 'تاشودة', nameFr: 'Tachouda', dairaAr: 'بئر العرش', dairaFr: 'Bir El Arch'},
  {id: 731, wilayaCode: 19, slug: 'tala-ifacene', nameAr: 'تالة إيفاسن', nameFr: 'Tala Ifacene', dairaAr: 'ماوكلان', dairaFr: 'Maoklane'},
  {id: 732, wilayaCode: 19, slug: 'taya', nameAr: 'الطاية', nameFr: 'Taya', dairaAr: 'حمام السخنة', dairaFr: 'Hammam Sokhna'},
  {id: 733, wilayaCode: 19, slug: 'tella', nameAr: 'التلة', nameFr: 'Tella', dairaAr: 'حمام السخنة', dairaFr: 'Hammam Sokhna'},
  {id: 734, wilayaCode: 19, slug: 'tizi-n-bechar', nameAr: 'تيزي نبشار', nameFr: 'Tizi N\'Béchar', dairaAr: 'عموشة', dairaFr: 'Amoucha'},
  {id: 841, wilayaCode: 23, slug: 'ain-el-berda', nameAr: 'عين الباردة', nameFr: 'Aïn El Berda', dairaAr: 'عين الباردة', dairaFr: 'Ain El Berda'},
  {id: 842, wilayaCode: 23, slug: 'annaba', nameAr: 'عنابة', nameFr: 'Annaba', dairaAr: 'عنابة', dairaFr: 'Annaba'},
  {id: 843, wilayaCode: 23, slug: 'berrahal', nameAr: 'برحال', nameFr: 'Berrahal', dairaAr: 'برحال', dairaFr: 'Berrahal'},
  {id: 844, wilayaCode: 23, slug: 'chetaibi', nameAr: 'شطايبي', nameFr: 'Chétaïbi', dairaAr: 'شطايبي', dairaFr: 'Chetaibi'},
  {id: 845, wilayaCode: 23, slug: 'cheurfa', nameAr: 'الشرفة', nameFr: 'Cheurfa', dairaAr: 'عين الباردة', dairaFr: 'Ain El Berda'},
  {id: 846, wilayaCode: 23, slug: 'el-bouni', nameAr: 'البوني', nameFr: 'El Bouni', dairaAr: 'البوني', dairaFr: 'El Bouni'},
  {id: 847, wilayaCode: 23, slug: 'eulma', nameAr: 'العلمة', nameFr: 'Eulma', dairaAr: 'عين الباردة', dairaFr: 'Ain El Berda'},
  {id: 848, wilayaCode: 23, slug: 'el-hadjar', nameAr: 'الحجار', nameFr: 'El Hadjar', dairaAr: 'الحجار', dairaFr: 'El Hadjar'},
  {id: 849, wilayaCode: 23, slug: 'oued-el-aneb', nameAr: 'واد العنب', nameFr: 'Oued El Aneb', dairaAr: 'برحال', dairaFr: 'Berrahal'},
  {id: 850, wilayaCode: 23, slug: 'seraidi', nameAr: 'سرايدي', nameFr: 'Séraïdi', dairaAr: 'عنابة', dairaFr: 'Annaba'},
  {id: 851, wilayaCode: 23, slug: 'sidi-amar', nameAr: 'سيدي عمار', nameFr: 'Sidi Amar', dairaAr: 'الحجار', dairaFr: 'El Hadjar'},
  {id: 852, wilayaCode: 23, slug: 'treat', nameAr: 'التريعات', nameFr: 'Treat', dairaAr: 'برحال', dairaFr: 'Berrahal'},
  {id: 887, wilayaCode: 25, slug: 'ain-abid', nameAr: 'عين عبيد', nameFr: 'Aïn Abid', dairaAr: 'عين عبيد', dairaFr: 'Ain Abid'},
  {id: 888, wilayaCode: 25, slug: 'ain-smara', nameAr: 'عين السمارة', nameFr: 'Aïn Smara', dairaAr: 'الخروب', dairaFr: 'El Khroub'},
  {id: 889, wilayaCode: 25, slug: 'ben-badis', nameAr: 'أبن باديس الهرية', nameFr: 'Ben Badis', dairaAr: 'عين عبيد', dairaFr: 'Ain Abid'},
  {id: 890, wilayaCode: 25, slug: 'beni-hamiden', nameAr: 'بني حميدان', nameFr: 'Beni Hamiden', dairaAr: 'زيغود يوسف', dairaFr: 'Zighoud Youcef'},
  {id: 891, wilayaCode: 25, slug: 'constantine', nameAr: 'قسنطينة', nameFr: 'Constantine', dairaAr: 'قسنطينة', dairaFr: 'Constantine'},
  {id: 892, wilayaCode: 25, slug: 'didouche-mourad', nameAr: 'ديدوش مراد', nameFr: 'Didouche Mourad', dairaAr: 'حامة بوزيان', dairaFr: 'Hamma Bouziane'},
  {id: 893, wilayaCode: 25, slug: 'el-khroub', nameAr: 'الخروب', nameFr: 'El Khroub', dairaAr: 'الخروب', dairaFr: 'El Khroub'},
  {id: 894, wilayaCode: 25, slug: 'hamma-bouziane', nameAr: 'حامة بوزيان', nameFr: 'Hamma Bouziane', dairaAr: 'حامة بوزيان', dairaFr: 'Hamma Bouziane'},
  {id: 895, wilayaCode: 25, slug: 'ibn-ziad', nameAr: 'ابن زياد', nameFr: 'Ibn Ziad', dairaAr: 'ابن زياد', dairaFr: 'Ibn Ziad'},
  {id: 896, wilayaCode: 25, slug: 'messaoud-boudjriou', nameAr: 'بوجريو مسعود', nameFr: 'Messaoud Boudjriou', dairaAr: 'ابن زياد', dairaFr: 'Ibn Ziad'},
  {id: 897, wilayaCode: 25, slug: 'ouled-rahmoune', nameAr: 'أولاد رحمون', nameFr: 'Ouled Rahmoune', dairaAr: 'الخروب', dairaFr: 'El Khroub'},
  {id: 898, wilayaCode: 25, slug: 'zighoud-youcef', nameAr: 'زيغود يوسف', nameFr: 'Zighoud Youcef', dairaAr: 'زيغود يوسف', dairaFr: 'Zighoud Youcef'},
  {id: 899, wilayaCode: 26, slug: 'ain-boucif', nameAr: 'عين بوسيف', nameFr: 'Aïn Boucif', dairaAr: 'عين بوسيف', dairaFr: 'Ain Boucif'},
  {id: 900, wilayaCode: 26, slug: 'ain-ouksir', nameAr: 'عين اقصير', nameFr: 'Aïn Ouksir', dairaAr: 'شلالة العذاورة', dairaFr: 'Chellalat El Adhaoura'},
  {id: 901, wilayaCode: 26, slug: 'aissaouia', nameAr: 'العيساوية', nameFr: 'Aïssaouia', dairaAr: 'تابلاط', dairaFr: 'Tablat'},
  {id: 902, wilayaCode: 26, slug: 'aziz', nameAr: 'عزيز', nameFr: 'Aziz', dairaAr: 'عزيز', dairaFr: 'Aziz'},
  {id: 903, wilayaCode: 26, slug: 'baata', nameAr: 'بعطة', nameFr: 'Baata', dairaAr: 'العمارية', dairaFr: 'El Omaria'},
  {id: 904, wilayaCode: 26, slug: 'ben-chicao', nameAr: 'بن شكاو', nameFr: 'Ben Chicao', dairaAr: 'وزرة', dairaFr: 'Ouzera'},
  {id: 905, wilayaCode: 26, slug: 'beni-slimane', nameAr: 'بني سليمان', nameFr: 'Beni Slimane', dairaAr: 'بني سليمان', dairaFr: 'Beni Slimane'},
  {id: 906, wilayaCode: 26, slug: 'berrouaghia', nameAr: 'البرواقية', nameFr: 'Berrouaghia', dairaAr: 'البرواقية', dairaFr: 'Berrouaghia'},
  {id: 907, wilayaCode: 26, slug: 'bir-ben-laabed', nameAr: 'بئر بن عابد', nameFr: 'Bir Ben Laabed', dairaAr: 'القلب الكبير', dairaFr: 'Guelb El Kebir'},
  {id: 908, wilayaCode: 26, slug: 'boghar', nameAr: 'بوغار', nameFr: 'Boghar', dairaAr: 'أولاد عنتر', dairaFr: 'Ouled Antar'},
  {id: 909, wilayaCode: 26, slug: 'bouaiche', nameAr: 'بوعيش', nameFr: 'Bouaiche', dairaAr: 'الشهبونية', dairaFr: 'Chahbounia'},
  {id: 910, wilayaCode: 26, slug: 'bouaichoune', nameAr: 'بوعيشون', nameFr: 'Bouaichoune', dairaAr: 'سي المحجوب', dairaFr: 'Si Mahdjoub'},
  {id: 911, wilayaCode: 26, slug: 'bouchrahil', nameAr: 'بوشراحيل', nameFr: 'Bouchrahil', dairaAr: 'سيدي نعمان', dairaFr: 'Sidi Naamane'},
  {id: 912, wilayaCode: 26, slug: 'boughzoul', nameAr: 'بوغزول', nameFr: 'Boughzoul', dairaAr: 'الشهبونية', dairaFr: 'Chahbounia'},
  {id: 913, wilayaCode: 26, slug: 'bouskene', nameAr: 'بوسكن', nameFr: 'Bouskene', dairaAr: 'بني سليمان', dairaFr: 'Beni Slimane'},
  {id: 914, wilayaCode: 26, slug: 'chabounia', nameAr: 'الشهبونية', nameFr: 'Chabounia', dairaAr: 'الشهبونية', dairaFr: 'Chahbounia'},
  {id: 915, wilayaCode: 26, slug: 'chellalat-el-adhaoura', nameAr: 'شلالة العذاورة', nameFr: 'Chellalat El Adhaoura', dairaAr: 'شلالة العذاورة', dairaFr: 'Chellalat El Adhaoura'},
  {id: 916, wilayaCode: 26, slug: 'cheniguel', nameAr: 'شنيقل', nameFr: 'Cheniguel', dairaAr: 'شلالة العذاورة', dairaFr: 'Chellalat El Adhaoura'},
  {id: 917, wilayaCode: 26, slug: 'derrag', nameAr: 'دراق', nameFr: 'Derrag', dairaAr: 'عزيز', dairaFr: 'Aziz'},
  {id: 918, wilayaCode: 26, slug: 'djouab', nameAr: 'جواب', nameFr: 'Djouab', dairaAr: 'السواقي', dairaFr: 'Souaghi'},
  {id: 919, wilayaCode: 26, slug: 'draa-esmar', nameAr: 'ذراع السمار', nameFr: 'Draa Esmar', dairaAr: 'المدية', dairaFr: 'Medea'},
  {id: 920, wilayaCode: 26, slug: 'el-azizia', nameAr: 'العزيزية', nameFr: 'El Azizia', dairaAr: 'العزيزية', dairaFr: 'El Azizia'},
  {id: 921, wilayaCode: 26, slug: 'el-guelbel-kebir', nameAr: 'القلب الكبير', nameFr: 'El Guelbel Kebir', dairaAr: 'القلب الكبير', dairaFr: 'Guelb El Kebir'},
  {id: 922, wilayaCode: 26, slug: 'el-hamdania', nameAr: 'الحمدانية', nameFr: 'El Hamdania', dairaAr: 'وزرة', dairaFr: 'Ouzera'},
  {id: 923, wilayaCode: 26, slug: 'el-haoudane', nameAr: 'الحوضان', nameFr: 'El Haoudane', dairaAr: 'تابلاط', dairaFr: 'Tablat'},
  {id: 924, wilayaCode: 26, slug: 'el-omaria', nameAr: 'العمارية', nameFr: 'El Omaria', dairaAr: 'العمارية', dairaFr: 'El Omaria'},
  {id: 925, wilayaCode: 26, slug: 'el-ouinet', nameAr: 'العوينات', nameFr: 'El Ouinet', dairaAr: 'عين بوسيف', dairaFr: 'Ain Boucif'},
  {id: 926, wilayaCode: 26, slug: 'hannacha', nameAr: 'حناشة', nameFr: 'Hannacha', dairaAr: 'عوامري', dairaFr: 'Ouamri'},
  {id: 927, wilayaCode: 26, slug: 'kef-lakhdar', nameAr: 'الكاف الاخضر', nameFr: 'Kef Lakhdar', dairaAr: 'عين بوسيف', dairaFr: 'Ain Boucif'},
  {id: 928, wilayaCode: 26, slug: 'khams-djouamaa', nameAr: 'خمس جوامع', nameFr: 'Khams Djouamaa', dairaAr: 'سيدي نعمان', dairaFr: 'Sidi Naamane'},
  {id: 929, wilayaCode: 26, slug: 'ksar-el-boukhari', nameAr: 'قصر البخاري', nameFr: 'Ksar El Boukhari', dairaAr: 'قصر البخاري', dairaFr: 'Ksar El Boukhari'},
  {id: 930, wilayaCode: 26, slug: 'maghraoua', nameAr: 'مغراوة', nameFr: 'Maghraoua', dairaAr: 'العزيزية', dairaFr: 'El Azizia'},
  {id: 931, wilayaCode: 26, slug: 'medea', nameAr: 'المدية', nameFr: 'Médéa', dairaAr: 'المدية', dairaFr: 'Medea'},
  {id: 932, wilayaCode: 26, slug: 'medjebar', nameAr: 'مجبر', nameFr: 'Medjebar', dairaAr: 'سغوان', dairaFr: 'Seghouane'},
  {id: 933, wilayaCode: 26, slug: 'mezerana', nameAr: 'مزغنة', nameFr: 'Mezerana', dairaAr: 'تابلاط', dairaFr: 'Tablat'},
  {id: 934, wilayaCode: 26, slug: 'm-fatha', nameAr: 'مفاتحة', nameFr: 'M\'fatha', dairaAr: 'قصر البخاري', dairaFr: 'Ksar El Boukhari'},
  {id: 935, wilayaCode: 26, slug: 'mihoub', nameAr: 'ميهوب', nameFr: 'Mihoub', dairaAr: 'العزيزية', dairaFr: 'El Azizia'},
  {id: 936, wilayaCode: 26, slug: 'ouamri', nameAr: 'عوامري', nameFr: 'Ouamri', dairaAr: 'عوامري', dairaFr: 'Ouamri'},
  {id: 937, wilayaCode: 26, slug: 'oued-harbil', nameAr: 'وادي حربيل', nameFr: 'Oued Harbil', dairaAr: 'عوامري', dairaFr: 'Ouamri'},
  {id: 938, wilayaCode: 26, slug: 'ouled-antar', nameAr: 'أولاد عنتر', nameFr: 'Ouled Antar', dairaAr: 'أولاد عنتر', dairaFr: 'Ouled Antar'},
  {id: 939, wilayaCode: 26, slug: 'ouled-bouachra', nameAr: 'أولاد بوعشرة', nameFr: 'Ouled Bouachra', dairaAr: 'سي المحجوب', dairaFr: 'Si Mahdjoub'},
  {id: 940, wilayaCode: 26, slug: 'ouled-brahim', nameAr: 'أولاد إبراهيم', nameFr: 'Ouled Brahim', dairaAr: 'العمارية', dairaFr: 'El Omaria'},
  {id: 941, wilayaCode: 26, slug: 'ouled-deid', nameAr: 'أولاد دايد', nameFr: 'Ouled Deid', dairaAr: 'البرواقية', dairaFr: 'Berrouaghia'},
  {id: 942, wilayaCode: 26, slug: 'ouled-emaaraf', nameAr: 'أولاد امعرف', nameFr: 'Ouled Emaaraf', dairaAr: 'عين بوسيف', dairaFr: 'Ain Boucif'},
  {id: 943, wilayaCode: 26, slug: 'ouled-hellal', nameAr: 'أولاد هلال', nameFr: 'Ouled Hellal', dairaAr: 'أولاد عنتر', dairaFr: 'Ouled Antar'},
  {id: 944, wilayaCode: 26, slug: 'oum-el-djellil', nameAr: 'أم الجليل', nameFr: 'Oum El Djellil', dairaAr: 'عزيز', dairaFr: 'Aziz'},
  {id: 945, wilayaCode: 26, slug: 'ouzera', nameAr: 'وزرة', nameFr: 'Ouzera', dairaAr: 'وزرة', dairaFr: 'Ouzera'},
  {id: 946, wilayaCode: 26, slug: 'rebaia', nameAr: 'الربعية', nameFr: 'Rebaia', dairaAr: 'البرواقية', dairaFr: 'Berrouaghia'},
  {id: 947, wilayaCode: 26, slug: 'saneg', nameAr: 'السانق', nameFr: 'Saneg', dairaAr: 'قصر البخاري', dairaFr: 'Ksar El Boukhari'},
  {id: 948, wilayaCode: 26, slug: 'sedraya', nameAr: 'سدراية', nameFr: 'Sedraya', dairaAr: 'القلب الكبير', dairaFr: 'Guelb El Kebir'},
  {id: 949, wilayaCode: 26, slug: 'seghouane', nameAr: 'سغوان', nameFr: 'Seghouane', dairaAr: 'سغوان', dairaFr: 'Seghouane'},
  {id: 950, wilayaCode: 26, slug: 'si-mahdjoub', nameAr: 'سي المحجوب', nameFr: 'Si Mahdjoub', dairaAr: 'سي المحجوب', dairaFr: 'Si Mahdjoub'},
  {id: 951, wilayaCode: 26, slug: 'sidi-demed', nameAr: 'سيدي دامد', nameFr: 'Sidi Demed', dairaAr: 'عين بوسيف', dairaFr: 'Ain Boucif'},
  {id: 952, wilayaCode: 26, slug: 'sidi-naamane', nameAr: 'سيدي نعمان', nameFr: 'Sidi Naamane', dairaAr: 'سيدي نعمان', dairaFr: 'Sidi Naamane'},
  {id: 953, wilayaCode: 26, slug: 'sidi-rabie', nameAr: 'سيدي الربيع', nameFr: 'Sidi Rabie', dairaAr: 'بني سليمان', dairaFr: 'Beni Slimane'},
  {id: 954, wilayaCode: 26, slug: 'sidi-zahar', nameAr: 'سيدي زهار', nameFr: 'Sidi Zahar', dairaAr: 'السواقي', dairaFr: 'Souaghi'},
  {id: 955, wilayaCode: 26, slug: 'sidi-ziane', nameAr: 'سيدي زيان', nameFr: 'Sidi Ziane', dairaAr: 'السواقي', dairaFr: 'Souaghi'},
  {id: 956, wilayaCode: 26, slug: 'souagui', nameAr: 'السواقي', nameFr: 'Souagui', dairaAr: 'السواقي', dairaFr: 'Souaghi'},
  {id: 957, wilayaCode: 26, slug: 'tablat', nameAr: 'تابلاط', nameFr: 'Tablat', dairaAr: 'تابلاط', dairaFr: 'Tablat'},
  {id: 958, wilayaCode: 26, slug: 'tafraout', nameAr: 'تفراوت', nameFr: 'Tafraout', dairaAr: 'شلالة العذاورة', dairaFr: 'Chellalat El Adhaoura'},
  {id: 959, wilayaCode: 26, slug: 'tamesguida', nameAr: 'تمسقيدة', nameFr: 'Tamesguida', dairaAr: 'المدية', dairaFr: 'Medea'},
  {id: 960, wilayaCode: 26, slug: 'tizi-mahdi', nameAr: 'تيزي مهدي', nameFr: 'Tizi Mahdi', dairaAr: 'وزرة', dairaFr: 'Ouzera'},
  {id: 961, wilayaCode: 26, slug: 'tletat-ed-douair', nameAr: 'ثلاث دوائر', nameFr: 'Tletat Ed Douair', dairaAr: 'سغوان', dairaFr: 'Seghouane'},
  {id: 962, wilayaCode: 26, slug: 'zoubiria', nameAr: 'الزبيرية', nameFr: 'Zoubiria', dairaAr: 'سغوان', dairaFr: 'Seghouane'},
  {id: 1110, wilayaCode: 31, slug: 'ain-biya', nameAr: 'عين البية', nameFr: 'Aïn Biya', dairaAr: 'بطيوة', dairaFr: 'Bethioua'},
  {id: 1111, wilayaCode: 31, slug: 'ain-kerma', nameAr: 'عين الكرمة', nameFr: 'Aïn Kerma', dairaAr: 'بوتليليس', dairaFr: 'Boutlelis'},
  {id: 1112, wilayaCode: 31, slug: 'ain-turk', nameAr: 'عين الترك', nameFr: 'Aïn Turk', dairaAr: 'عين الترك', dairaFr: 'Ain Turk'},
  {id: 1113, wilayaCode: 31, slug: 'arzew', nameAr: 'أرزيو', nameFr: 'Arzew', dairaAr: 'أرزيو', dairaFr: 'Arzew'},
  {id: 1114, wilayaCode: 31, slug: 'ben-freha', nameAr: 'بن فريحة', nameFr: 'Ben Freha', dairaAr: 'قديل', dairaFr: 'Gdyel'},
  {id: 1115, wilayaCode: 31, slug: 'bethioua', nameAr: 'بطيوة', nameFr: 'Bethioua', dairaAr: 'بطيوة', dairaFr: 'Bethioua'},
  {id: 1116, wilayaCode: 31, slug: 'bir-el-djir', nameAr: 'بئر الجير', nameFr: 'Bir El Djir', dairaAr: 'بئر الجير', dairaFr: 'Bir El Djir'},
  {id: 1117, wilayaCode: 31, slug: 'boufatis', nameAr: 'بوفاتيس', nameFr: 'Boufatis', dairaAr: 'وادي تليلات', dairaFr: 'Oued Tlelat'},
  {id: 1118, wilayaCode: 31, slug: 'bou-sfer', nameAr: 'بوسفر', nameFr: 'Bou Sfer', dairaAr: 'عين الترك', dairaFr: 'Ain Turk'},
  {id: 1119, wilayaCode: 31, slug: 'boutlelis', nameAr: 'بوتليليس', nameFr: 'Boutlélis', dairaAr: 'بوتليليس', dairaFr: 'Boutlelis'},
  {id: 1120, wilayaCode: 31, slug: 'el-ancor', nameAr: 'العنصر', nameFr: 'El Ançor', dairaAr: 'عين الترك', dairaFr: 'Ain Turk'},
  {id: 1121, wilayaCode: 31, slug: 'el-braya', nameAr: 'البراية', nameFr: 'El Braya', dairaAr: 'وادي تليلات', dairaFr: 'Oued Tlelat'},
  {id: 1122, wilayaCode: 31, slug: 'el-kerma', nameAr: 'الكرمة', nameFr: 'El Kerma', dairaAr: 'السانية', dairaFr: 'Es Senia'},
  {id: 1123, wilayaCode: 31, slug: 'es-senia', nameAr: 'السانية', nameFr: 'Es Sénia', dairaAr: 'السانية', dairaFr: 'Es Senia'},
  {id: 1124, wilayaCode: 31, slug: 'gdyel', nameAr: 'قديل', nameFr: 'Gdyel', dairaAr: 'قديل', dairaFr: 'Gdyel'},
  {id: 1125, wilayaCode: 31, slug: 'hassi-ben-okba', nameAr: 'حاسي بن عقبة', nameFr: 'Hassi Ben Okba', dairaAr: 'بئر الجير', dairaFr: 'Bir El Djir'},
  {id: 1126, wilayaCode: 31, slug: 'hassi-bounif', nameAr: 'حاسي بونيف', nameFr: 'Hassi Bounif', dairaAr: 'بئر الجير', dairaFr: 'Bir El Djir'},
  {id: 1127, wilayaCode: 31, slug: 'hassi-mefsoukh', nameAr: 'حاسي مفسوخ', nameFr: 'Hassi Mefsoukh', dairaAr: 'قديل', dairaFr: 'Gdyel'},
  {id: 1128, wilayaCode: 31, slug: 'marsat-el-hadjadj', nameAr: 'مرسى الحجاج', nameFr: 'Marsat El Hadjadj', dairaAr: 'بطيوة', dairaFr: 'Bethioua'},
  {id: 1129, wilayaCode: 31, slug: 'mers-el-kebir', nameAr: 'المرسى الكبير', nameFr: 'Mers El Kébir', dairaAr: 'عين الترك', dairaFr: 'Ain Turk'},
  {id: 1130, wilayaCode: 31, slug: 'misserghin', nameAr: 'مسرغين', nameFr: 'Misserghin', dairaAr: 'بوتليليس', dairaFr: 'Boutlelis'},
  {id: 1131, wilayaCode: 31, slug: 'oran', nameAr: 'وهران', nameFr: 'Oran', dairaAr: 'وهران', dairaFr: 'Oran'},
  {id: 1132, wilayaCode: 31, slug: 'oued-tlelat', nameAr: 'وادي تليلات', nameFr: 'Oued Tlelat', dairaAr: 'وادي تليلات', dairaFr: 'Oued Tlelat'},
  {id: 1133, wilayaCode: 31, slug: 'sidi-ben-yebka', nameAr: 'سيدي بن يبقى', nameFr: 'Sidi Ben Yebka', dairaAr: 'أرزيو', dairaFr: 'Arzew'},
  {id: 1134, wilayaCode: 31, slug: 'sidi-chami', nameAr: 'سيدي الشحمي', nameFr: 'Sidi Chami', dairaAr: 'السانية', dairaFr: 'Es Senia'},
  {id: 1135, wilayaCode: 31, slug: 'tafraoui', nameAr: 'طفراوي', nameFr: 'Tafraoui', dairaAr: 'وادي تليلات', dairaFr: 'Oued Tlelat'}
] as const satisfies readonly CommuneRecord[];
